### ISSUE TITLE
View Details button (visible on hover) should be a link not a button

### ISSUE THREAD

**Issue by wyze** [TreasureProject/treasure-marketplace#218]
We should keep the appearance the same (as a button), but render it as a link to allow users to open it in a new tab like previously.

**Comment by zelkibuilds** [comment]
@wyze Would like to know how you like this best. Right clicking on the `View details` link makes it so:

a) the on-hover overlay changes back to 0 opacity since it is no longer being hovered but focused
<img width="417" alt="Screenshot 2022-03-28 at 23 47 29" src="https://user-images.githubusercontent.com/94715286/160499827-8257848c-441f-474f-8509-753ac796b28e.png">

b) the on-hover overlay persists after the right click (since it now shows on focus as well) but persists if the user closes the menu. This makes it so if the user hovers another card both of them show the overlay

First image shows the right click state, second one shows the menu closed while the user hovers another card.

<img width="490" alt="Screenshot 2022-03-28 at 23 44 00" src="https://user-images.githubusercontent.com/94715286/160499851-2be3f823-fa03-48b2-a497-0fd1f1a785b1.png">
<img width="403" alt="Screenshot 2022-03-28 at 23 44 14" src="https://user-images.githubusercontent.com/94715286/160499868-1e036fdc-188d-44fc-96d9-bacfeb657fd9.png">

I'm going to open a PR for the 2nd version and we can just delete the additional styles of b) in order to get the styles of a)

**Comment by jcheese1** [comment]
why did i make this a button
